// <auto-generated />
namespace EducationSystem.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class CreateRelationshipBetweenAuthorAndCourse1 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(CreateRelationshipBetweenAuthorAndCourse1));
        
        string IMigrationMetadata.Id
        {
            get { return "202111040941488_CreateRelationshipBetweenAuthorAndCourse1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
